version: '3.8'
services:
  brightsign_rss: 
    # image: fractalartinteractive/brightsign_rss
    build: 
      dockerfile: Dockerfile
    volumes: 
      - ./media:/usr/share/media
    ports: 
      - 8080:8080
    environment:
    - HOSTNAME=10.224.10.53
    - PORT=8080
    restart: always
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 80:8080
    volumes:
      - ./media:/data
      - ./fb_config:/config
    environment:
      - FB_BASEURL=/
      - FB_NOAUTH=noauth
    restart: always
    